version: "3.8"

services:
    app:
        image: php:8.1-fpm
        container_name: laravel-app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on:
            - db
        environment:
            DB_CONNECTION: pgsql # IMPORTANT: tell Laravel to use pgsql
            DB_HOST: db
            DB_PORT: 5432 # PostgreSQL default port
            DB_DATABASE: uniqhire
            DB_USERNAME: postgres # default PostgreSQL user
            DB_PASSWORD: lance123
        command: >
            sh -c "
              apt-get update &&
              apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev zip unzip git curl libpq-dev &&
              docker-php-ext-configure gd --with-freetype --with-jpeg &&
              docker-php-ext-install pdo pdo_pgsql gd zip &&
              curl -sS https://getcomposer.org/installer | php &&
              mv composer.phar /usr/local/bin/composer &&
              composer install &&
              php artisan migrate &&
              php artisan serve --host=0.0.0.0 --port=8000
            "

    db:
        image: postgres:15
        container_name: laravel-db
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: uniqhire
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: lance123
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
