version: "3.8"

services:
    app:
        image: php:8.1-fpm
        container_name: laravel-app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: uniqhire
            DB_USERNAME: root
            DB_PASSWORD: lance123
        command: >
            sh -c "
              apt-get update &&
              apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev zip unzip git curl &&
              docker-php-ext-configure gd --with-freetype --with-jpeg &&
              docker-php-ext-install pdo pdo_mysql gd &&
              curl -sS https://getcomposer.org/installer | php &&
              mv composer.phar /usr/local/bin/composer &&
              composer install &&
              php artisan migrate &&
              php artisan serve --host=0.0.0.0 --port=8000
            "

    db:
        image: mysql:5.7
        container_name: laravel-db
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: lance123
            MYSQL_DATABASE: uniqhire
            MYSQL_USER: root
            MYSQL_PASSWORD: lance123
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
